In [1]:
import numpy as np
import pandas as pd
data=pd.read_csv('http://iali.in/datasets/Social_Network_Ads.csv')
data.head()
data.shape


(400, 5)

In [0]:
x=data.iloc[:, :-1].values
y=data.iloc[:, 4].values

In [4]:
x

array([[15624510, 'Male', 19, 19000],
       [15810944, 'Male', 35, 20000],
       [15668575, 'Female', 26, 43000],
       ...,
       [15654296, 'Female', 50, 20000],
       [15755018, 'Male', 36, 33000],
       [15594041, 'Female', 49, 36000]], dtype=object)

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
lblencoder=LabelEncoder()
x[:, 1]=lblencoder.fit_transform(x[:, 3])
onehotencoder= OneHotEncoder(categorical_features=[1])
x=onehotencoder.fit_transform(x).toarray()

TypeError: ignored

In [7]:
pip install -U scikit-learn==0.20

     |████████████████████████████████| 5.3MB 6.5MB/s 
  Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1


In [1]:
import numpy as np
import pandas as pd
data=pd.read_csv('http://iali.in/datasets/Social_Network_Ads.csv')
data.head()
data.shape
x=data.iloc[:, :-1].values
y=data.iloc[:, 4].values
x
y
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
lblencoder=LabelEncoder()
x[:, 1]=lblencoder.fit_transform(x[:, 1])
onehotencoder= OneHotEncoder(categorical_features=[1])
x=onehotencoder.fit_transform(x).toarray()


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:385: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [2]:
x.astype(int)

array([[       0,        1, 15624510,       19,    19000],
       [       0,        1, 15810944,       35,    20000],
       [       1,        0, 15668575,       26,    43000],
       ...,
       [       1,        0, 15654296,       50,    20000],
       [       0,        1, 15755018,       36,    33000],
       [       1,        0, 15594041,       49,    36000]])

In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [4]:
len(x_train)

280

In [5]:
from sklearn.linear_model import LinearRegression
MLR=LinearRegression()
MLR.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [6]:
print(f'constant={MLR.intercept_}')
print(f'coefficients={MLR.coef_}')

constant=2.353622349290239
coefficients=[-7.30171293e-04  7.30171293e-04 -2.07195409e-07  2.64630033e-02
  3.72340916e-06]


In [0]:
y_predict=MLR.predict(x_test)

In [8]:
df=pd.DataFrame(data=y_test, columns=['y_test'])
df['y_predict']=y_predict
df

y_test  y_predict
0         0   0.213895
1         0   0.301551
2         0   0.290924
3         0   0.179997
4         0   0.225145
..      ...        ...
115       0   0.653349
116       1   0.754650
117       0   0.232223
118       0   0.639557
119       1   0.548137

[120 rows x 2 columns]